name: Waka Readme
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '*/1 * * * *'
 
jobs:
  update-readme:
    name: Update this repo's README 
    runs-on: ubuntu-latest
    steps:
      - uses: xzdry/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.XZDRY }}
          SHOW_TOTAL: true
          TIME_RANGE: last_7_days
